namespace FighterSim
{
    static public class Names
    {
        public static string[] enemyNames = new string[]
        {
            "Google Assistant",    
            "Siri Apple",
            "Maria Jonsson",    
            "Vilma Ulf",        
            "Viviana Westergren",   
            "Anne Bergqvist",   
            "Katja Holmquist",  
            "Clara Backström",  
            "Ragierdh Selander",    
            "Anne Selander",    
            "Andrea Brahe", 
            "Gabriella Bloch",  
            "Ellena Lindskog",  
            "Patricia Posse",   
            "Cecilia Larsson",  
            "Adele Jakobsson",  
            "Isabelle Lundgren",    
            "Viveka Ahlund",    
            "Erika Ljungberg",  
            "Linda Sjöholm",    
            "Elliot Haglund",   
            "Göran Palme",  
            "Gudhlek Hedman",   
            "Robert Nordlund",  
            "Ludvig Bergkvist", 
            "Josef Lagerquist", 
            "Simon Vikström",   
            "William Widforss", 
            "Peter Wahlberg",   
            "Love Lind",    
            "Miranda Westermark",   
            "Cornelia Nordström",   
            "Ragiähl Degermark",    
            "Bea Hellquist",    
            "Selma Lund",   
            "June Schauman",    
            "Astrid Dahlin",    
            "Lucia Hedström",   
            "Ulla Wahlgren",    
            "Pia Dahlgren", 
            "Ögge Sandell", 
            "Björn Nilsson",    
            "Ernst Hedberg",    
            "Isac Hagelin", 
            "Felix Lundgren",   
            "Johan Palmstruch", 
            "Johannes Lundberg",    
            "Hersten Göransson",    
            "Åke Lundin",   
            "Önne Lundell", 
        };
        public static string[] playerNames = new string[]
        {
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Arda",
            "Martin",
        };
    }
}